### ISSUE TITLE
Demo notebook AttributeError: 'NoneType' object has no attribute 'predict'

### ISSUE THREAD

**Issue by vzickus** [matjesg/DeepFLaSH#1]
When trying to run the Demo notebook I get the following:

> fatal: destination path 'DeepFLaSH' already exists and is not an empty directory.
> Please provide allowed model name: cFOS_Wue, cFOS_Inns1, cFOS_Inns2, cFOS_Mue, Parv or new
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-8536b5617cbc> in <module>()
>      17 
>      18 # Predict masks with the unet
> ---> 19 pred_train = model.predict(np.asarray(img_list))
>      20 msk_train_list = [pred_train[i] for i in range(pred_train.shape[0])]
>      21 
> 
> AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by matjesg** [comment]
There is a new version of the notebook available. Please reset your Google Colab Runtime before running the notebook.(https://colab.research.google.com/github/matjesg/DeepFLaSH/blob/master/DeepFLaSH.ipynb)
